name: Parser compilation and query file check

on: [push, pull_request]

jobs:
  check_compilation_unix_like:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        cc: [ gcc ]

    name: Parser compilation
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.5.0

      - name: Install and prepare Neovim
        run: |
          bash ./test/scripts/ci-install-${{ matrix.os }}.sh

      - name: Compile parsers Unix like
        run: |
          nvim --headless -c "TSInstallSync all" -c "q"

      - name: Check query files (Unix)
        env:
          ALLOWED_INSTALLATION_FAILURES: haskell
        run: nvim --headless -c "luafile ./test/scripts/check-queries.lua" -c "q"

      - uses: actions/upload-artifact@v2
        with:
          name: parsers-${{ matrix.os }}-${{ matrix.cc }}-x86_64
          path: parser/*

